development:
  adapter: async

test:
  adapter: async

# production:
#   adapter: redis
#   url: <%= ENV['redis://rediscloud:0eQ8Pil79sdJVouJxk9hJeeLJed4GfPb@redis-12051.c2.eu-west-1-3.ec2.cloud.redislabs.com:12051'] %>

production:
  adapter: redis
  url: redis://rediscloud:0eQ8Pil79sdJVouJxk9hJeeLJed4GfPb@redis-12051.c2.eu-west-1-3.ec2.cloud.redislabs.com:12051
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: flambu-test-app_production
